version: '3.9'
services:
  nginx:
    container_name: fastapi-hw-web
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
      - api
  redis:
    container_name: fastapi-hw-redis
    image: redis:alpine
  db:
    container_name: fastapi-hw-db
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
  api:
    container_name: fastapi-hw-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
# sh -c "alembic revision --autogenerate -m "Initial commit"\
# && alembic upgrade head && gunicorn main:app --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres-data: