version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:12
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user 
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres_password
      - postgres_db
      - postgres_user


  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "alembic revision --autogenerate -m "Initial commit" && alembic upgrade head"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env

secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  