name: Build, Test, and Deploy FastAPI-HW
on:
  push:
    branches: [feature/own-auth]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Injecting env vars
        run: |
          echo "POSTGRES_DB=postgres
                POSTGRES_USER=postgres
                POSTGRES_PASSWORD=789456
                POSTGRES_PORT=5432
                DOMAIN=fastapi-hw-db
                SQLALCHEMY_DATABASE_URL=${{secrets.SQLALCHEMY_DATABASE_URL}}
                SECRET_KEY=very_secret_key
                ALGORITHM=HS256
                MAIL_USERNAME=example@test.ua
                MAIL_PASSWORD=secret
                MAIL_FROM=example@test.ua
                MAIL_PORT=888
                MAIL_SERVER=some server
                MAIL_FROM_NAME=Example email
                REDIS_HOST=localhost
                REDIS_PORT=6379
                CLOUDINARY_NAME=some name
                CLOUDINARY_API_KEY=333333
                CLOUDINARY_API_SECRET=some secret
                CLOUDINARY_URL=url" >> .env && echo ${SQLALCHEMY_DATABASE_URL}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Redis container
        run: docker run -d --name redis -p 6379:6379 redis
      - name: Test with pytest
        run: pytest