name: Build, Test, and Deploy FastAPI-HW
on:
  push:
    branches: [feature/own-auth]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Injecting env vars
        run: |
          echo "REDIS_HOST=localhost 
                REDIS_PORT=6379" >> .env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Redis container
        run: docker run -d --name redis -p 6379:6379 redis
      - name: Test with pytest
        run: pytest

