name: Build, Test, and Deploy FastAPI-HW
on:
  push:
    branches: [main]
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Injecting env vars
        run: |
          echo "DATABASE_NAME=test_coredb
          DATABASE_USER=test_core
          DATABASE_PASSWORD=12345678
          DATABASE_HOST=test_fastapi-hw_db
          DATABASE_PORT=5432
          POSTGRES_USER=test_core
          POSTGRES_PASSWORD=12345678
          POSTGRES_DB=test_coredb
          " >> .env